apiVersion: v1
kind: Service
metadata:
  name: azure-app
  namespace: app
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: azure-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-app
  template:
    metadata:
      labels:
        app: azure-app
    spec:
      containers:
      - name: azure-app
        image: nuriarcdemoacr.azurecr.io/azapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
